#if !canImport(ObjectiveC)
import XCTest

extension ASTContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ASTContextTests = [
        ("testNamedParams", testNamedParams),
        ("testSubcommands", testSubcommands),
        ("testTrailingBooleanNamedParam", testTrailingBooleanNamedParam),
    ]
}

extension CommandLineApplicationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandLineApplicationTests = [
        ("testPostProcessingStage", testPostProcessingStage),
        ("testRunWithoutNamedParams", testRunWithoutNamedParams),
        ("testTreeConstruction", testTreeConstruction),
    ]
}

extension LexerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LexerTests = [
        ("testBoolean", testBoolean),
        ("testDecimal", testDecimal),
        ("testInt", testInt),
        ("testNonContextuals", testNonContextuals),
        ("testPeek", testPeek),
        ("testString", testString),
    ]
}

extension NamedParamCheckerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NamedParamCheckerTests = [
        ("testTypeCheckingFail", testTypeCheckingFail),
        ("testTypeCheckingOK", testTypeCheckingOK),
    ]
}

extension SourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SourceTests = [
        ("testMultipleBlocks", testMultipleBlocks),
        ("testSingeBlock", testSingeBlock),
    ]
}

extension UnnamedParamTypeCheckerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnnamedParamTypeCheckerTests = [
        ("testCombinedFailure", testCombinedFailure),
        ("testCombinedSuccess", testCombinedSuccess),
        ("testEmpty", testEmpty),
        ("testMultipleRecurrsingSuccess", testMultipleRecurrsingSuccess),
        ("testNonRecurringSuccess", testNonRecurringSuccess),
        ("testSingleRecurringFailure", testSingleRecurringFailure),
        ("testSingleRecurringSuccess", testSingleRecurringSuccess),
        ("testUnderflow", testUnderflow),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ASTContextTests.__allTests__ASTContextTests),
        testCase(CommandLineApplicationTests.__allTests__CommandLineApplicationTests),
        testCase(LexerTests.__allTests__LexerTests),
        testCase(NamedParamCheckerTests.__allTests__NamedParamCheckerTests),
        testCase(SourceTests.__allTests__SourceTests),
        testCase(UnnamedParamTypeCheckerTests.__allTests__UnnamedParamTypeCheckerTests),
    ]
}
#endif
